### PR TITLE
fix no filename extension error

### LINKED ISSUE #12: fails with filenames with no extensions
if the files associated with assets in Contentful do not have an extension, the tool fails.

### PR DESCRIPTION
**Pull request by cachrisman**
fixes #12

### CODE REVIEW

File: src/app/modules/assets/components/Assets.js [hunk 1]
```diff
@@ -28,7 +28,7 @@ export default class Assets extends Component {
       const localeFile = Object.keys(file)[0]
       const localeTitle = Object.keys(title)[0]
       const localizedTitle = title[localeTitle]
-      const ext = /\.(.*)$/.exec(file[localeFile].fileName)[1]
+      const ext = file[localeFile].fileName.split('.').slice(1).join('') || "no extension"
```
Comment (Khaledgarbaya) [inline src/app/modules/assets/components/Assets.js]: Hey @cachrisman this won't work if you have a filename like `my.example.file.js`
a better approach would be 
```js
const fileName = file[localeFile].fileName
const ext = fileName.slice((fileName.lastIndexOf(".") - 1 >>> 0) + 2)
```

**Review by Khaledgarbaya — CHANGES_REQUESTED** [review]

File: src/app/modules/assets/components/Assets.js (hunk 1 above)
Comment (axe312ger) [reply src/app/modules/assets/components/Assets.js]: ☝️

**Review by Khaledgarbaya — APPROVED** [review]
